POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "username": "testa46456456aja2",
  "first_name": "Pekka2",
  "last_name": "Testaaja2",
  "email": "pekka.testaaja2@test.com",
  "password": "salainen"
}

###
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testaaja2",
  "password": "salainen"
}

###
GET http://localhost:8000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjYzMzE3LCJpYXQiOjE3MzkyNjE1MTcsImp0aSI6IjRhNGVjY2Y5NmE4MjRkYjI5NGMwNDllOTE4N2RhYzIzIiwidXNlcl9pZCI6Mn0.zyfCboSb3lT7j7Dxjqw6Z7wFVxpYPjBLEYp6KLVMGJE

#user should not be able to delete other user
###
DELETE http://localhost:8000/api/users/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjYyNjg5LCJpYXQiOjE3MzkyNjA4ODksImp0aSI6IjM0MTE0YWU4NzA4MjQwN2E5YTJhMTQ4ZmY5ZWY4ZDBiIiwidXNlcl9pZCI6MX0.QOuTdc1Q24dE_BhbYtmzFHAut1WXXvwETE2gdWEjyyg